"""Entrypoint for LLM Tests Backend."""

from typing import Dict, List

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from langchain_impl.openai.simple_chat import OpenAiMessage, OpenAiSimpleChat

app = FastAPI(title="LLM Tests")

origins = [
    "http://localhost:5173",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/contexts")
def list_available_contexts() -> List[Dict[str, str]]:
    """Returns the list of available contexts to be used in the chat.

    Returns:
        A list containing dictionaries describing the context personas available to be
        used in the chat.
    """
    return [
        {
            "context": "high_school_counselor",
            "readable": "High school conselour"
        }
    ]


class OpenAiPayload(BaseModel):
    """OpenAi chat model payload.
    
    Attributes:
        messages: List of OpenAiMessage accumulated in the chat context.
        context_name: contex persona.
    """
    messages: List[OpenAiMessage]
    context_name: str


@app.post("/openai-messages")
def send_openai_message(openai_payload: OpenAiPayload) -> OpenAiMessage:
    """Returns OpenAiMessage containing the response for the messages received.
    
    Params:
        openai_payload: OpenAiPayload containing the messages.
    
    Returns:
        OpenAiMessage with the content of the response generated by openai model based
        on the list of messages and context persona received.
    """
    chat = OpenAiSimpleChat()
    chat_response = chat.chat(openai_payload.messages, openai_payload.context_name)
    return OpenAiMessage(sender='ai', content=chat_response.content)
